# Generated by Django 3.1.7 on 2022-01-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20220122_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
