# Generated by Django 3.1.7 on 2022-01-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_auto_20220123_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='poll',
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='231548', editable=False, max_length=6, unique=True),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='poll',
        ),
    ]
