# Generated by Django 3.1.7 on 2022-01-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_auto_20220123_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='257368', editable=False, max_length=6, unique=True),
        ),
    ]
