# Generated by Django 3.1.7 on 2022-01-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_auto_20220123_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='688086', editable=False, max_length=6, unique=True),
        ),
    ]
